# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 910296635ee5a924b2f01d8dfb1d0cfb7c2699cbde32e535fb4982bd655419e19ee1214d2fd375276ce1df183d59445b00bb1396540335185e0fb222ff9903af

test:
  secret_key_base: 61cb55304ce2109869fe921408fa63332aaf6052e4bdac2f04ed01c96bd4f40af5a8897808f35e1d533b156d759dfa213a7bf91d5285fc2a7c8e3347fab00337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
